parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: portal
    database_user: portal
    database_password: enovance
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 65f2b10a2fbc9b08a99e87917d429ecf5
    database_path: null
