enovance_user:
    resource: "@EnovanceUserBundle/Resources/config/routing.yml"
    prefix:   /

enovance_log:
    resource: "@EnovanceLogBundle/Resources/config/routing.yml"
    prefix:   /

enovance_infrastructure:
    resource: "@EnovanceInfrastructureBundle/Resources/config/routing.yml"
    prefix:   /

enovance_numeter:
    resource: "@EnovanceNumeterBundle/Resources/config/routing.yml"
    prefix:   /

enovance_portal:
    resource: "@EnovancePortalBundle/Resources/config/routing.yml"
    prefix:   /

root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect 
        route: enovance_portal_dashboard_index
        permanent: true

