enovance_log:
    resource: "@EnovanceLogBundle/Resources/config/routing.yml"
    prefix:   /

enovance_infrastructure:
    resource: "@EnovanceInfrastructureBundle/Resources/config/routing.yml"
    prefix:   /

enovance_numeter:
    resource: "@EnovanceNumeterBundle/Resources/config/routing.yml"
    prefix:   /

enovance_user:
    resource: "@EnovanceUserBundle/Resources/config/routing.yml"
    prefix:   /

enovance_portal:
    resource: "@EnovancePortalBundle/Resources/config/routing.yml"
    prefix:   /

login_check:
    pattern: /login_check

########### FOS USER BUNDLE ############
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
