jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512
#        Enovance\User\LdapUser: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        chain_provider:
#            chain:
#                providers: [fos_userbundle, fr3d_ldapbundle]
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
#        fr3d_ldapbundle:
#            id: fr3d_ldap.security.user.provider
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/(en|fr|es|de)/(login$|password/reset)
            anonymous: true

        main:
            pattern: ^/
            #fr3d_ldap:  ~
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                always_use_default_target_path: true
                default_target_path: enovance_portal_dashboard_index
                use_referer: true
                target_path_parameter: redirect_url
                remember_me: false             
            logout:
                path: /logout
                target: root
            anonymous: false

    access_control:
        - { path: ^/(en|fr|de|es)/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|fr|de|es)/password/reset, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|fr|de|es)/admin/, role: ROLE_ADMIN }
