parameters:
#    enovance_log.example.class: Enovance\LogBundle\Example

services:
#    enovance_log.example:
#        class: %enovance_log.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
