Enovance\InfrastructureBundle\Entity\Host:
    type: entity
    table: Hosts
    repositoryClass: Enovance\InfrastructureBundle\Entity\HostRepository
    indexes:
        name_index:
            columns: [ name ]
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: '50'
        addr:
            type: string
            length: '250'
        hostUID:
            type: string
            length: '50'
    manyToOne:
        storage:
            targetEntity: Enovance\NumeterBundle\Entity\Storage
            inversedBy: hosts
        test:
            targetEntity: Enovance\LogBundle\Entity\Test
            inversedBy: hosts
    lifecycleCallbacks: {  }
