enovance_portal_dashboard_index:
    pattern:  /{_locale}/dashboard
    defaults: { _controller: EnovancePortalBundle:Dashboard:index }

enovance_portal_dashboard_default:
    pattern:  /{_locale}
    defaults: { _controller: EnovancePortalBundle:Dashboard:index }

enovance_portal_admin_index:
    pattern:  /{_locale}/admin
    defaults: { _controller: EnovancePortalBundle:Admin:index }
