enovance_portal_dashboard_index:
    pattern:  /dashboard
    defaults: { _controller: EnovancePortalBundle:Dashboard:index }

enovance_portal_dashboard_default:
    pattern:  /
    defaults: { _controller: EnovancePortalBundle:Dashboard:index }

