enovance_portal_dashboard_index:
    pattern:  /dashboard
    defaults: { _controller: EnovancePortalBundle:Dashboard:index }

enovance_portal_dashboard_default:
    pattern:  /
    defaults: { _controller: EnovancePortalBundle:Dashboard:index }

enovance_portal_admin_index:
    pattern:  /admin
    defaults: { _controller: EnovancePortalBundle:Admin:index }
