parameters:
#    enovance_portal.example.class: Enovance\PortalBundle\Example

services:
#    enovance_portal.example:
#        class: %enovance_portal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
