enovance_numeter_graph_index:
    pattern:  /{_locale}/graph/
    defaults: { _controller: EnovanceNumeterBundle:Default:index }

enovance_admin_graphs:
    pattern:  /{_locale}/admin/graphs
    defaults: { _controller: EnovanceNumeterBundle:Admin:graphs }
