parameters:
    enovance_numeter.configure_menu_listener: Enovance\NumeterBundle\EventListener\ConfigureMenuListener

#    enovance_numeter.example:
#        class: %enovance_numeter.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    enovance_numeter.configure_menu_listener:
        class: %enovance_numeter.configure_menu_listener%
        tags:
          - { name: kernel.event_listener, event: enovance_portal.menu_configure, method: onMenuConfigure }
