Enovance\UserBundle\Entity\Company:
    type: entity
    table: portal_companies
    repositoryClass: Enovance\UserBundle\Entity\CompanyRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: '50'
        address:
            type: string
            length: '150'
            nullable: TRUE
        city:
            type: string
            length: '50'
            nullable: TRUE
        country:
            type: string
            length: '50'
            nullable: TRUE
        phone:
            type: string
            length: '20'
            nullable: TRUE
    oneToMany:
        users:
            targetEntity: Enovance\UserBundle\Entity\User
            mappedBy: company
    manyToMany:
         hosts:
             targetEntity: Enovance\InfrastructureBundle\Entity\Host
             inversedBy: companies
             joinTable:
                 name: host_company
                 joinColumns:
                     company_id:
                         referencedColumnName: id
                 inverseJoinColumns:
                     host_id:
                         referencedColumnName: id
    lifecycleCallbacks: {  }
