Enovance\UserBundle\Entity\Group:
    type: entity
    table: portal_groups
    repositoryClass: Enovance\UserBundle\Entity\GroupRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToMany:
         permissions:
             targetEntity: Enovance\UserBundle\Entity\Permission
             inversedBy: groups
             joinTable:
                 name: portal_groups_permissions
                 joinColumns:
                     group_id:
                         referencedColumnName: id
                 inverseJoinColumns:
                     permission_id:
                         referencedColumnName: id
    lifecycleCallbacks: {  }
