fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile


fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/password/reset

enovance_admin_users:
    pattern:  /{_locale}/admin/users
    defaults: { _controller: EnovanceUserBundle:Admin:users }

enovance_admin_user_new:
    pattern: /{_locale}/admin/users/new
    defaults:  { _controller: EnovanceUserBundle:Admin:newUser }

enovance_admin_user_edit:
    pattern: /{_locale}/admin/users/edit/{id}
    defaults:  { _controller: EnovanceUserBundle:Admin:editUser }

enovance_admin_user_delete:
    pattern: /{_locale}/admin/users/delete/{id}
    defaults:  { _controller: EnovanceUserBundle:Admin:deleteUser }


enovance_admin_groups:
    pattern:  /{_locale}/admin/groups
    defaults: { _controller: EnovanceUserBundle:Admin:groups }

enovance_admin_companies:
    pattern:  /{_locale}/admin/companies
    defaults: { _controller: EnovanceUserBundle:Admin:companies }
