fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile


fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/password/reset

enovance_admin_users:
    pattern:  /{_locale}/admin/users
    defaults: { _controller: EnovanceUserBundle:Admin:users }

enovance_admin_groups:
    pattern:  /{_locale}/admin/groups
    defaults: { _controller: EnovanceUserBundle:Admin:groups }

enovance_admin_companies:
    pattern:  /{_locale}/admin/companies
    defaults: { _controller: EnovanceUserBundle:Admin:companies }

_change_language:
    pattern: /lang/{_locale}
    defaults:  { _controller: EnovanceUserBundle:Default:changeLanguage, _locale: en }
    requirements:
      _locale: ^en|fr|es|de$
