parameters:
#    enovance_user.example.class: Enovance\UserBundle\Example

services:
#    enovance_user.example:
#        class: %enovance_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
